version: 1

picture: configs/example.jpg

profil:
  lastname: DOE
  firstname: Jane
  position:
    en: Software Developer
    fr: Développeur de logiciel
  email: dada.fafa@example.com
  phone: 123 456 789
  address: Here
  age: 0x18

skills:
  - field:
      en: Computer Language
      fr: Langage informatique
    skills:
      - C
      - C++
      - Rust

  - field: Software
    skills:
      - Git
      - CMake
      - en: Dada
        fr: Fafa

interests:
  en:
    - Programming
    - Cupcakes
  fr:
    - Pain
    - Vin

experiences:
  - start: 2021
    stop: 2023
    months: 18
    # break: true
    company: Acme Corporation
    position: Software Engineer
    description:
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Dada Fafa gaga haha jaja kaka lala mama.

  - start: 2020
    months: 6
    company:
      en: FooBarEn
      fr: FooBarFr
    position:
      en: Software Developer
      fr: Développeur de logiciel
    description:
      en:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        - Dada Fafa gaga haha jaja kaka lala mama.
      fr:
        - J'aime le pain, le fromage et le vin.

educations:
  - start: 2015
    stop: 2017
    school: Fafa
    schooling: Dada
    description:
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Dada Fafa gaga haha jaja kaka lala mama.

  - start: 2015
    stop: 2017
    school: Acme School
    schooling: Computer Engineer
    description:
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Dada Fafa gaga haha jaja kaka lala mama.

projects:
  - start: 2022
    stop: Still WIP
    title: Typst Resume
    repository: https://github.com/0x546974616e/typst-resume
    description:
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Dada Fafa gaga haha jaja kaka lala mama.

  - start: 2019
    title: Super Project
    description:
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Dada Fafa gaga haha jaja kaka lala mama.